import pyttsx3

engine = pyttsx3.init()
text = "春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。"*5
#engine.save_to_file(text, "合成语音200.wav")
#engine.runAndWait()
engine.setProperty("rate", 179)
engine.save_to_file(text, "合成语音179.wav")
engine.runAndWait()
engine.setProperty("rate", 223)
engine.save_to_file(text, "合成语音223.wav")
engine.runAndWait()
engine.setProperty("rate", 53)
engine.save_to_file(text, "合成语音53.wav")
engine.runAndWait()
engine.setProperty("rate", 400)
engine.save_to_file(text, "合成语音400.wav")
engine.runAndWait()
engine.setProperty("rate", 523)
engine.save_to_file(text, "合成语音523.wav")
engine.runAndWait()
engine.setProperty("rate", 450)
engine.save_to_file(text, "合成语音450.wav")
engine.runAndWait()
engine.setProperty("rate", 410)
engine.save_to_file(text, "合成语音410.wav")
engine.runAndWait()
engine.setProperty("rate", 420)
engine.save_to_file(text, "合成语音420.wav")
engine.runAndWait()
engine.setProperty("rate", 430)
engine.save_to_file(text, "合成语音430.wav")
engine.runAndWait()
engine.setProperty("rate", 440)
engine.save_to_file(text, "合成语音440.wav")
engine.runAndWait()
engine.setProperty("rate", 460)
engine.save_to_file(text, "合成语音460.wav")
engine.runAndWait()
engine.setProperty("rate", 700)
engine.save_to_file(text, "合成语音700.wav")
engine.runAndWait()
engine.setProperty("rate", 800)
engine.save_to_file(text, "合成语音800.wav")
engine.runAndWait()
